### ISSUE TITLE
Suggestion to change the  URL of your blog in readme file

### ISSUE THREAD

**Issue by piyaln** [ArunaLakmal/Dockerfile-Terraform-Ansible-AWS#20]
Hi Aruna
Thanks for sharing the details
It is better if you could change the URL of your blog in readme file to
https://www.techcrumble.net/2020/05/simple-github-action-to-build-the-docker-images/

Currently its given as https://www.techcrumble.net/ which shows the home page of Techcrumble.net site. Then users has to do a search to find your specific blog.

Regards
Piyal

**Comment by arunalakmal** [comment]
Hi Piyal

Thanks for bringing it up. I'll update the readme with the post url. Thanks.
